---
- hosts: localhost
  connection: local
  gather_facts: False

  tasks:

  - include_vars: vars.yml

  - name: Create a resource group
    azure_rm_resourcegroup:
      name: "{{ resource_group }}"
      location: westus
      tags:
          delete: never

  - name: Create storage account
    azure_rm_storageaccount:
      resource_group: "{{ resource_group }}"
      name: "{{ storage_account }}"
      account_type: Standard_LRS

  - name: Create virtual network
    azure_rm_virtualnetwork:
      resource_group: "{{ resource_group }}"
      name: "{{ network_id }}"
      address_prefixes: "10.10.0.0/16"

  - name: Add subnet
    azure_rm_subnet:
      resource_group: "{{ resource_group }}"
      name: "{{ subnet_id }}"
      address_prefix: "10.10.0.0/16"
      virtual_network: "{{ network_id }}"

  - name: Create security group that allows SSH and HTTP
    azure_rm_securitygroup:
      resource_group: "{{ resource_group }}"
      name: "{{ security_group_id }}"
      rules:
        - name: SSH
          protocol: Tcp
          destination_port_range: 22
          access: Allow
          priority: 101
          direction: Inbound
        - name: HTTP
          protocol: Tcp
          destination_port_range: 80
          access: Allow
          priority: 102
          direction: Inbound

  - name: Create public ips
    azure_rm_publicipaddress:
      resource_group: "{{ resource_group }}"
      allocation_method: Static
      name: "{{ item.ip }}"
      domain_name_label: "{{ item.name }}"
    with_items: "{{ instances }}"

  - name: Create NIC
    azure_rm_networkinterface:
      resource_group: "{{ resource_group }}"
      name: "{{ item.interface }}"
      virtual_network: "{{ network_id }}"
      subnet: "{{ subnet_id }}"
      public_ip_name: "{{ item.ip }}"
      security_group: "{{ security_group_id }}"
    with_items: "{{ instances }}"

  - name: Create virtual machine
    azure_rm_virtualmachine:
      resource_group: "{{ resource_group }}"
      name: "{{ item.name }}"
      vm_size: "{{ item.size }}"
      storage_account: "{{ storage_account }}"
      storage_container: "{{ item.name }}"
      storage_blob: "{{ item.name }}.vhd"
      admin_username: ansible
      admin_password: Ansible_demo!
      network_interfaces: "{{ item.interface }}"
      image:
        offer: CentOS
        publisher: OpenLogic
        sku: '7.3'
        version: latest
    with_items: "{{ instances }}"
